name: Actions sync
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
jobs:

  sync-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v1.1.0
        with:
          COMMIT_MESSAGE: "Update Checkstyle files"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USERNAME: micronaut-build
          GIT_EMAIL: "micronaut-build@users.noreply.github.com"
          SRC_REPO: micronaut-projects/micronaut-project-template
          FILE_PATTERNS: |-
            ^config/.*$
          TARGET_REPOS: |-
            micronaut-projects/micronaut-rabbitmq
            micronaut-projects/micronaut-sql
            micronaut-projects/micronaut-data
            micronaut-projects/micronaut-servlet
            micronaut-projects/micronaut-nats
            micronaut-projects/micronaut-gcp
            micronaut-projects/micronaut-azure
