name: Files sync
on:
  schedule:
    - cron: '0 8 * * *'  
  push:
    branches:
      - master
    paths:
      - ".github/workflows/**"
jobs:
  sync-files:
    runs-on: ubuntu-latest
    steps:
      - uses: adrianjost/files-sync-action@v1.1.0
        with:
          COMMIT_MESSAGE: "Update common files"
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_USERNAME: micronaut-build
          GIT_EMAIL: "micronaut-build@users.noreply.github.com"
          SRC_REPO: micronaut-projects/micronaut-project-template
          FILE_PATTERNS: |-
            ^\.github\/workflows\/central-sync\.yml$
            ^\.github\/workflows\/dependency-check\.yml$
            ^\.github\/workflows\/dependency-update\.yml$
            ^\.github\/workflows\/gradle\.yml$
            ^\.github\/workflows\/label-sync\.yml$
            ^\.github\/workflows\/release-notes\.yml$
            ^\.github\/workflows\/release\.yml$
            ^gradle/.*$
            ^.gitignore$
            ^gradlew$
            ^gradlew.bat$
            ^ISSUE_TEMPLATE.md$
            ^LICENSE$
            ^config\/HEADER$
            ^config\/spotless\.license\.java$
            ^config\/checkstyle\/checkstyle\.xml$
          TARGET_REPOS: |-
            micronaut-projects/micronaut-rabbitmq
            micronaut-projects/micronaut-sql
            micronaut-projects/micronaut-data
            micronaut-projects/micronaut-servlet
            micronaut-projects/micronaut-micrometer
            micronaut-projects/micronaut-nats
            micronaut-projects/micronaut-gcp
            micronaut-projects/micronaut-kafka
            micronaut-projects/micronaut-kotlin
            micronaut-projects/micronaut-azure
            micronaut-projects/micronaut-groovy
            micronaut-projects/micronaut-test
            micronaut-projects/micronaut-netflix



