name: Go

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - uses: actions/checkout@v4
    - name: Get dependencies
      run: |
        go mod tidy
    - name: Build
      run: go build -v .
