name: Secret Sync
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/secrets-sync.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.0
        env:
          GPG_FILE: ${{ secrets.GPG_FILE }} 
        with:
          SECRETS: |
            ^GPG_FILE*
          REPOSITORIES: |
             micronaut-projects/micronaut-test
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CONCURRENCY: 10

         
