uses: google/secrets-sync-action
  with:
    SECRETS: |
    ^GPG_FILE*
    REPOSITORIES: |
    micronaut-projects/micronaut-test
    DRY_RUN: true
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    CONCURRENCY: 10
