name: Secret Sync
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/secrets-sync.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action
        with:
          SECRETS: |
            ^GPG_FILE*
          REPOSITORIES: |
             micronaut-projects/micronaut-test
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CONCURRENCY: 10
