name: Secret Sync
on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/secrets-sync.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.0
        env:
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }} 
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }} 
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          GPG_FILE: ${{ secrets.GPG_FILE }} 
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }} 
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }} 
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }} 
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }} 
        with:
          SECRETS: |
            ^BINTRAY_.*
            ^GH_TOKEN$
            ^GPG_.*
            ^SONATYPE_.*
          REPOSITORIES: |
             micronaut-projects/micronaut-test
             micronaut-projects/micronaut-views
             micronaut-projects/micronaut-aws
             micronaut-projects/micronaut-openapi
             micronaut-projects/micronaut-sql            
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CONCURRENCY: 10

         
